import type { Participant } from "@/types";

export const mockSheetParticipants: Omit<Participant, "status" | "isOfficer" | "appNotes" | "carId" | "seatIndex" | "checkInState">[] = [
  {
    id: "1",
    name: "Alex Nguyen",
    phone: "(949) 555-1001",
    email: "alex@example.com",
    timestamp: "2026-02-20T09:00:00.000Z",
    driver: true,
    seats: 4,
    selfDriver: false,
    riderPreferences: "prefers quiet ride",
    preferredRidePartners: ["Maya Patel", "Jordan Lee"],
  },
  {
    id: "2",
    name: "Maya Patel",
    phone: "(949) 555-1002",
    email: "maya@example.com",
    timestamp: "2026-02-20T09:02:00.000Z",
    driver: false,
    seats: 0,
    selfDriver: false,
    riderPreferences: "likes music",
    preferredRidePartners: ["Alex Nguyen"],
  },
  {
    id: "3",
    name: "Jordan Lee",
    phone: "(949) 555-1003",
    email: "jordan@example.com",
    timestamp: "2026-02-20T09:05:00.000Z",
    driver: false,
    seats: 0,
    selfDriver: false,
    riderPreferences: "can leave early",
    preferredRidePartners: ["Alex Nguyen", "Maya Patel"],
  },
  {
    id: "4",
    name: "Priya Shah",
    phone: "(949) 555-1004",
    email: "priya@example.com",
    timestamp: "2026-02-20T09:10:00.000Z",
    driver: true,
    seats: 3,
    selfDriver: false,
    riderPreferences: "likes music",
    preferredRidePartners: [],
  },
  {
    id: "5",
    name: "Diego Ramos",
    phone: "(949) 555-1005",
    email: "diego@example.com",
    timestamp: "2026-02-20T09:12:00.000Z",
    driver: false,
    seats: 0,
    selfDriver: false,
    riderPreferences: "prefers quiet ride",
    preferredRidePartners: ["Hannah Kim"],
  },
  {
    id: "6",
    name: "Hannah Kim",
    phone: "(949) 555-1006",
    email: "hannah@example.com",
    timestamp: "2026-02-20T09:13:00.000Z",
    driver: false,
    seats: 0,
    selfDriver: false,
    riderPreferences: "likes music",
    preferredRidePartners: ["Diego Ramos"],
  },
  {
    id: "7",
    name: "Samantha Lopez",
    phone: "(626) 029-1007",
    email: "samantha@example.com",
    timestamp: "2026-02-20T09:15:00.000Z",
    driver: true,
    seats: 0,
    selfDriver: true,
    riderPreferences: "",
    preferredRidePartners: [],
  },
];
